2025-01-07 10:55:56,732 - ERROR - main - main.py - Error in connection to db: port should be of type int
2025-01-07 10:57:11,389 - ERROR - main - main.py - Error in connection to db: port should be of type int
2025-01-07 11:00:48,023 - ERROR - main - main.py - Error in connection to db(host: 127.0.0.1, user: root, pass: admin, db: mydb, port: 3306): port should be of type int
2025-01-08 15:26:28,964 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Авиакомпания` (`Название авиакомпании`) VALUES (%s) with parameters: ('Тестовая3',) error: (1062, "Duplicate entry 'Тестовая3' for key 'авиакомпания.PRIMARY'")
2025-01-09 23:48:11,342 - ERROR - main - main.py - Error in connection to db(host: 127.0.0.1, user: root, pass: admin, db: mydb, port: 3306): 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2025-01-09 23:50:50,574 - ERROR - main - main.py - Error in connection to db(host: 127.0.0.1, user: root, pass: admin, db: mydb, port: 3306): 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2025-01-09 23:50:53,110 - ERROR - main - main.py - Error in connection to db(host: 127.0.0.1, user: root, pass: admin, db: mydb, port: 3306): 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2025-01-10 20:42:32,469 - ERROR - main - main.py - Error in connection to db(host: 127.0.0.1, user: root, pass: admin, db: mydb, port: 3306): 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2025-01-10 20:42:44,294 - ERROR - main - main.py - Error in connection to db(host: 127.0.0.1, user: root, pass: admin, db: mydb, port: 3306): 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2025-01-11 01:23:06,322 - ERROR - main - main.py - Error in select_fetchone in: 
        INSERT INTO `Тариф` 
        (`Название тарифа`, `Допустимый вес багажа`,`Допустимый вес ручной клади`, `Доп.плата за питомца`, 
        `Возможность изменения билета`, `Выбор места`, `Возможность возврата`,
        `Кол-во начисления бонусов`, `Возможность повышения класса`, `Наличие открытой даты вылета`,
        `Приоритетная регистрация`, `Приоритетный досмотр`, `Приоритетная посадка`,
        `Приоритетное обслуживание багажа`, `Код тарифа`, `Авиакомпания_Название авиакомпании`
        )
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
         with parameters: ('По умолчанию', 20.0, 20.0, True, True, True, True, 1000.0, True, True, True, True, True, True, '6a8cdf5fe77d6831aed50039f3f83bcf', 'Тестовая') error: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`mydb`.`тариф`, CONSTRAINT `fk_Тариф_Авиакомпания1` FOREIGN KEY (`Авиакомпания_Название авиакомпании`) REFERENCES `авиакомпан?')
2025-01-11 15:43:08,562 - ERROR - main - main.py - Error in connection to db(host: 127.0.0.1, user: root, pass: admin, db: mydb, port: 3306): 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2025-01-11 15:43:16,699 - ERROR - main - main.py - Error in connection to db(host: 127.0.0.1, user: root, pass: admin, db: mydb, port: 3306): 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2025-01-11 15:54:42,817 - ERROR - main - main.py - Error in select_fetchone in: 
        INSERT INTO `Тариф` 
        (`Название тарифа`, `Допустимый вес багажа`,`Допустимый вес ручной клади`, `Доп.плата за питомца`, 
        `Возможность изменения билета`, `Выбор места`, `Возможность возврата`,
        `Кол-во начисления бонусов`, `Возможность повышения класса`, `Наличие открытой даты вылета`,
        `Приоритетная регистрация`, `Приоритетный досмотр`, `Приоритетная посадка`,
        `Приоритетное обслуживание багажа`, `Код тарифа`, `Авиакомпания_Название авиакомпании`
        )
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
         with parameters: ('Экономный', 20.0, 20.0, False, True, False, True, 100.0, False, False, False, True, False, False, '2200fc1abbb3ffd59f6d8ac56d240064', 'Тестовая') error: (1062, "Duplicate entry 'Тестовая' for key 'тариф.PRIMARY'")
2025-01-11 16:06:35,281 - ERROR - main - main.py - Error in connection to db(host: 127.0.0.1, user: root, pass: admin, db: mydb, port: 3306): 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2025-01-11 16:14:32,044 - ERROR - main - main.py - Error in select_fetchone in: 
        INSERT INTO `Тариф` 
        (`Название тарифа`, `Допустимый вес багажа`,`Допустимый вес ручной клади`, `Доп.плата за питомца`, 
        `Возможность изменения билета`, `Выбор места`, `Возможность возврата`,
        `Кол-во начисления бонусов`, `Возможность повышения класса`, `Наличие открытой даты вылета`,
        `Приоритетная регистрация`, `Приоритетный досмотр`, `Приоритетная посадка`,
        `Приоритетное обслуживание багажа`, `Код тарифа`, `Авиакомпания_Название авиакомпании`
        )
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
         with parameters: ('Богатый', 100.0, 100.0, False, True, True, True, 10000.0, True, True, True, True, True, True, '2216fd1562e0c7ebdab621b4a21afd58', 'Тестовая') error: (1264, "Out of range value for column 'Допустимый вес багажа' at row 1")
2025-01-11 16:16:10,939 - ERROR - main - main.py - Error in select_fetchone in: 
        INSERT INTO `Тариф` 
        (`Название тарифа`, `Допустимый вес багажа`,`Допустимый вес ручной клади`, `Доп.плата за питомца`, 
        `Возможность изменения билета`, `Выбор места`, `Возможность возврата`,
        `Кол-во начисления бонусов`, `Возможность повышения класса`, `Наличие открытой даты вылета`,
        `Приоритетная регистрация`, `Приоритетный досмотр`, `Приоритетная посадка`,
        `Приоритетное обслуживание багажа`, `Код тарифа`, `Авиакомпания_Название авиакомпании`
        )
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
         with parameters: ('Богатый', 100.0, 100.0, False, True, True, True, 100.0, True, True, True, True, True, True, 'fd2dcdd148eacbb6ce9841159fd0366e', 'Тестовая') error: (1264, "Out of range value for column 'Допустимый вес багажа' at row 1")
2025-01-11 16:29:33,228 - ERROR - main - main.py - Error in select_fetchone in: DELET FROM `Тариф` WHERE `Код тарифа`=%s with parameters: ('f7a3e38499bcede1066615a2abf8c9f1',) error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELET FROM `Тариф` WHERE `Код тарифа`='f7a3e38499bcede1066615a2abf' at line 1")
2025-01-12 01:02:38,086 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Полет` (`Номер рейса`, `Дата вылета`, `Время вылета`, `Кол-во пассажиров`, `Место отправления`, `Место назначения`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('Мурманск', 'Москва', '6483491b600efefc6f8bd5095e2fa232', datetime.date(2025, 1, 22), datetime.time(12, 0), 23) error: (1292, "Incorrect date value: 'Москва' for column 'Дата вылета' at row 1")
2025-01-12 13:24:27,047 - ERROR - main - main.py - Error in select_fetchall in: SELECT * FROM `Полет` ORDER BY `Дата вылета` DESC, `Время вылета` DESC with parameters: () error: (1146, "Table 'mydb.полет' doesn't exist")
2025-01-12 16:58:54,390 - ERROR - main - main.py - Error in select_fetchall in: SELECT * FROM `Полет` ORDER BY `Дата вылета` DESC, `Время вылета` DESC with parameters: () error: (1146, "Table 'mydb.полет' doesn't exist")
2025-01-12 17:04:52,007 - ERROR - main - main.py - Error in select_fetchall in: SELECT * FROM `Полет` ORDER BY `Дата вылета` DESC, `Время вылета` DESC with parameters: () error: (1146, "Table 'mydb.полет' doesn't exist")
2025-01-12 17:05:40,601 - ERROR - main - main.py - Error in select_fetchall in: SELECT * FROM `Полет` ORDER BY `Дата вылета` DESC, `Время вылета` DESC with parameters: () error: (1146, "Table 'mydb.полет' doesn't exist")
2025-01-12 19:07:34,685 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Полет` (`Авиакомпания_Название авиакомпании`, `Номер рейса`, `Дата вылета`, `Время вылета`, `Кол-во пассажиров`, `Место отправления`, `Место назначения`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('S7 Airlines', 'fc6559cf054d106c2da65affe4409d9f', datetime.date(2025, 1, 22), datetime.time(12, 0), 25, 'Мурманск', 'Москва') error: not all arguments converted during string formatting
2025-01-13 00:33:54,354 - ERROR - main - main.py - Error in select_fetchall in: SELECT * FROM `Билет` ORDER BY `Номер билета` WHERE `Номер полета`=%s with parameters: ('fc5892becaf12a3c298ad1c8688d1d49',) error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `Номер полета`='fc5892becaf12a3c298ad1c8688d1d49'' at line 1")
2025-01-13 00:33:56,220 - ERROR - main - main.py - Error in select_fetchall in: SELECT * FROM `Билет` ORDER BY `Номер билета` WHERE `Номер полета`=%s with parameters: ('fc5892becaf12a3c298ad1c8688d1d49',) error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `Номер полета`='fc5892becaf12a3c298ad1c8688d1d49'' at line 1")
2025-01-13 00:34:20,117 - ERROR - main - main.py - Error in select_fetchall in: SELECT * FROM `Билет` ORDER BY `Номер билета` WHERE `Номер полета`=%s with parameters: ('fc5892becaf12a3c298ad1c8688d1d49',) error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `Номер полета`='fc5892becaf12a3c298ad1c8688d1d49'' at line 1")
2025-01-13 00:35:25,463 - ERROR - main - main.py - Error in select_fetchall in: SELECT * FROM `Билет` ORDER BY `Номер билета` WHERE `Номер полета`=%s with parameters: ('fc5892becaf12a3c298ad1c8688d1d49',) error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `Номер полета`='fc5892becaf12a3c298ad1c8688d1d49'' at line 1")
2025-01-13 00:35:47,937 - ERROR - main - main.py - Error in select_fetchall in: SELECT * FROM `Билет` ORDER BY `Номер билета` WHERE `Номер полета`=%s with parameters: ('fc5892becaf12a3c298ad1c8688d1d49',) error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `Номер полета`='fc5892becaf12a3c298ad1c8688d1d49'' at line 1")
2025-01-13 00:36:11,885 - ERROR - main - main.py - Error in select_fetchall in: SELECT * FROM `Билет` ORDER BY `Номер билета` WHERE `Номер полета`=%s with parameters: ('fc5892becaf12a3c298ad1c8688d1d49',) error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `Номер полета`='fc5892becaf12a3c298ad1c8688d1d49'' at line 1")
2025-01-14 00:33:03,266 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Первый класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-0', Decimal('30000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,276 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Первый класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-1', Decimal('30000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,286 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Первый класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-2', Decimal('30000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,296 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Первый класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-3', Decimal('30000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,316 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Первый класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-4', Decimal('30000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,324 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Бизнес класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-5', Decimal('20000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,334 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Бизнес класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-6', Decimal('20000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,365 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Бизнес класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-7', Decimal('20000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,396 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Бизнес класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-8', Decimal('20000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,406 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Бизнес класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-9', Decimal('20000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,425 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Эконом-премиум класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-10', Decimal('15000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,434 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Эконом-премиум класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-11', Decimal('15000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,442 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Эконом-премиум класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-12', Decimal('15000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,452 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Эконом-премиум класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-13', Decimal('15000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,471 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Эконом-премиум класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-14', Decimal('15000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,482 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Эконом класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-15', Decimal('10000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,492 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Эконом класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-16', Decimal('10000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,502 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Эконом класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-17', Decimal('10000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,514 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Эконом класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-18', Decimal('10000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-14 00:33:03,548 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Билет` (`Номер полета`, `Класс`, `Ндд`, `Ндп`, `Номер билета`, `Цена билета`) VALUES (%s,%s,%s,%s,%s,%s) with parameters: ('892b6156011e0f4006a3ecdde68988ad', 'Эконом класс', datetime.date(2025, 1, 14), datetime.date(2025, 1, 18), '892b6156011e0f4006a3ecdde68988ad-19', Decimal('10000.02')) error: (1364, "Field 'Сдан' doesn't have a default value")
2025-01-17 22:58:00,753 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Покупка` (`Номер заказа`, `Финальная цена`, `Дата заказа`, `Время заказа`, `Кассир_Номер кассира`, `Полет_Номер рейса`, `Билет_Номер билета`, `Пассажир_Серия`, `Пассажир_Номер`, `Статус покупки`) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) with parameters: ('3c521e87dbcfe298ec9126699545f2f5', Decimal('10000.00'), datetime.date(2025, 1, 17), datetime.time(22, 58, 0, 746315), '2', '015934f1008293e85af46f68d58216ff', '015934f1008293e85af46f68d58216ff-0', 111111, 22222, 'Офомрлена') error: (1054, "Unknown column 'Статус покупки' in 'field list'")
2025-01-17 22:58:00,766 - ERROR - main - main.py - Error in select_fetchone in: UPDATE `Билет` SET `Наличие багажа`=%s, `Наличие ручной клади`=%s, `Наличие питомца`=%s, `Тариф_Код тарифа`=%s, `Выкуплены`=%s, WHERE `Номер билета`=%s with parameters: ('015934f1008293e85af46f68d58216ff-0', 'b0aefbce986c1dc8128401a518d94fb2', True, True, False, True) error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `Номер билета`=1' at line 1")
2025-01-17 23:34:12,196 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Покупка` (`Номер заказа`, `Финальная цена`, `Дата заказа`, `Время заказа`, `Кассир_Номер кассира`, `Полет_Номер рейса`, `Билет_Номер билета`, `Пассажир_Серия`, `Пассажир_Номер`, `Статус покупки`) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) with parameters: ('f0fb658ab8248b107c3bd586a355534b', Decimal('10000.00'), datetime.date(2025, 1, 17), datetime.time(23, 34, 12, 193950), '2', '015934f1008293e85af46f68d58216ff', '015934f1008293e85af46f68d58216ff-0', 11111111, 222222, 'Офомрлена') error: (1054, "Unknown column 'Статус покупки' in 'field list'")
2025-01-17 23:34:12,206 - ERROR - main - main.py - Error in select_fetchone in: UPDATE `Билет` SET `Наличие багажа`=%s, `Наличие ручной клади`=%s, `Наличие питомца`=%s, `Тариф_Код тарифа`=%s, `Выкуплены`=%s, WHERE `Номер билета`=%s with parameters: (True, True, True, 'b0aefbce986c1dc8128401a518d94fb2', True, '015934f1008293e85af46f68d58216ff-0') error: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `Номер билета`='015934f1008293e85af46f68d58216ff-0'' at line 1")
2025-01-18 15:41:01,456 - ERROR - main - main.py - Error in select_fetchone in: DELETE FROM `Кассир` WHERE `Номер кассира`=%s with parameters: (2,) error: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`mydb`.`покупка`, CONSTRAINT `fk_Покупка_Кассир1` FOREIGN KEY (`Кассир_Номер кассира`) REFERENCES `кассир` (`Номер кассира`))')
2025-01-18 15:41:04,329 - ERROR - main - main.py - Error in select_fetchone in: DELETE FROM `Кассир` WHERE `Номер кассира`=%s with parameters: (2,) error: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`mydb`.`покупка`, CONSTRAINT `fk_Покупка_Кассир1` FOREIGN KEY (`Кассир_Номер кассира`) REFERENCES `кассир` (`Номер кассира`))')
2025-01-18 17:42:25,553 - ERROR - main - main.py - Error in select_fetchone in: INSERT INTO `Покупка` (`Номер заказа`, `Финальная цена`, `Дата заказа`, `Время заказа`, `Кассир_Номер кассира`, `Виза_Номер визы`, `Полет_Номер рейса`, `Билет_Номер билета`, `Пассажир_Серия`, `Пассажир_Номер`, `Статус покупки`) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) with parameters: ('9a4be98e07ab545fe2b4e50a493364a9', Decimal('20000.00'), datetime.date(2025, 1, 18), datetime.time(17, 42, 25, 551278), '1', '8900022', 'e620851359793dd958e89da4abb62630', 'e620851359793dd958e89da4abb62630-19', 99999, 333333, 'Офомрлена') error: (1054, "Unknown column 'Статус покупки' in 'field list'")
2025-01-18 17:49:46,020 - ERROR - main - main.py - Error in select_fetchone in: UPDATE `Покупка` SET `Статус покупкки`=%s WHERE `Номер заказа`=%s with parameters: ('Отмена', {}) error: dict can not be used as parameter
2025-01-18 17:54:52,260 - ERROR - main - main.py - Error in select_fetchone in: UPDATE `Покупка` SET `Статус покупкки`=%s WHERE `Номер заказа`=%s with parameters: ('Отмена', {'number_purchase': 'da17e27850c6c98a4ea764a060fbfd9a', 'final_price': Decimal('20000.00'), 'date': datetime.date(2025, 1, 18), 'time': datetime.timedelta(seconds=64482), 'cashier_id': 1, 'visa_number': '8900022', 'flight_number': 'e620851359793dd958e89da4abb62630', 'ticket_number': 'e620851359793dd958e89da4abb62630-19', 'passenger_number': '56575', 'passenger_series': '55556476745', 'status': 'Офомрлена'}) error: dict can not be used as parameter
2025-01-18 18:10:24,733 - ERROR - main - main.py - Error in select_fetchone in: UPDATE `Покупка` SET `Статус покупкки`=%s WHERE `Номер заказа`=%s with parameters: ('Отмена', {'number_purchase': '72f5a45a53848f685e62ed07146d3431', 'final_price': Decimal('10015.00'), 'date': datetime.date(2025, 1, 18), 'time': datetime.timedelta(seconds=65412), 'cashier_id': 1, 'visa_number': '8900022', 'flight_number': 'e620851359793dd958e89da4abb62630', 'ticket_number': 'e620851359793dd958e89da4abb62630-19', 'passenger_number': '23', 'passenger_series': '23', 'status': 'Офомрлена'}) error: dict can not be used as parameter
2025-01-18 19:00:11,442 - ERROR - main - main.py - Error in connection to db(host: 127.0.0.1, user: root, pass: admin, db: mydb, port: 3306): (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
